/*
 * This file was automatically generated by EvoSuite
 * Mon May 15 14:06:34 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import static org.junit.Assert.*;
import edu.osu.cs362.Appt;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true)
public class Appt_ESTest extends Appt_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 0, 12, 12, "", "");
      assertEquals(0, appt0.getStartDay());
      
      appt0.setStartDay(1);
      assertEquals(1, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Appt appt0 = new Appt(11, 11, 1945, 11, 11, "}o&Bn,V)k&", "}o&Bn,V)k&");
      assertEquals(1945, appt0.getStartDay());
      
      appt0.setStartDay(11);
      boolean boolean0 = appt0.getValid();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Appt appt0 = new Appt(23, 23, (-976), 1701, (-1069), "", "!pe0/ok;/d_,6");
      String string0 = appt0.getTitle();
      assertEquals(23, appt0.getStartMinute());
      assertEquals(1701, appt0.getStartMonth());
      assertEquals(23, appt0.getStartHour());
      assertEquals("", string0);
      assertFalse(appt0.getValid());
      assertEquals(-1069, appt0.getStartYear());
      assertEquals("!pe0/ok;/d_,6", appt0.getDescription());
      assertEquals(-976, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Appt appt0 = new Appt(0, 59, 0, 0, 0, "", "");
      int int0 = appt0.getStartYear();
      assertEquals(0, appt0.getStartDay());
      assertFalse(appt0.getValid());
      assertEquals(0, int0);
      assertEquals(0, appt0.getStartHour());
      assertEquals(59, appt0.getStartMinute());
      assertEquals(0, appt0.getStartMonth());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 0, 12, 12, "", "");
      int int0 = appt0.getStartYear();
      assertEquals(12, appt0.getStartMonth());
      assertEquals(0, appt0.getStartHour());
      assertEquals(0, appt0.getStartDay());
      assertEquals(0, appt0.getStartMinute());
      assertEquals(12, int0);
      assertFalse(appt0.getValid());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Appt appt0 = new Appt((-755), (-755), 0, 0, 0, "", "");
      int int0 = appt0.getStartMonth();
      assertEquals(-755, appt0.getStartMinute());
      assertEquals(0, appt0.getStartYear());
      assertEquals(0, int0);
      assertFalse(appt0.getValid());
      assertEquals(0, appt0.getStartDay());
      assertEquals(-755, appt0.getStartHour());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Appt appt0 = new Appt((-48), (-48), (-48), (-48), (-48), "", "");
      int int0 = appt0.getStartMonth();
      assertEquals((-48), int0);
      assertEquals(-48, appt0.getStartHour());
      assertEquals(-48, appt0.getStartYear());
      assertFalse(appt0.getValid());
      assertEquals(-48, appt0.getStartMinute());
      assertEquals(-48, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 0, 0, 0, ",jJA::2t@Sn9", (String) null);
      int int0 = appt0.getStartMinute();
      assertEquals(0, appt0.getStartHour());
      assertEquals(0, appt0.getStartYear());
      assertEquals(0, appt0.getStartMonth());
      assertEquals(",jJA::2t@Sn9", appt0.getTitle());
      assertEquals(0, int0);
      assertFalse(appt0.getValid());
      assertEquals("", appt0.getDescription());
      assertEquals(0, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Appt appt0 = new Appt(0, (-1338), 0, 1225, (-1338), "", "3");
      int int0 = appt0.getStartMinute();
      assertEquals("3", appt0.getDescription());
      assertEquals("", appt0.getTitle());
      assertEquals(0, appt0.getStartHour());
      assertFalse(appt0.getValid());
      assertEquals(1225, appt0.getStartMonth());
      assertEquals(-1338, appt0.getStartYear());
      assertEquals(0, appt0.getStartDay());
      assertEquals((-1338), int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 0, 0, 0, "", "");
      int int0 = appt0.getStartHour();
      assertEquals(0, appt0.getStartYear());
      assertEquals(0, appt0.getStartMonth());
      assertEquals(0, appt0.getStartMinute());
      assertFalse(appt0.getValid());
      assertEquals(0, appt0.getStartDay());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Appt appt0 = new Appt(1, 1, 1, 2859, 0, (String) null, (String) null);
      int int0 = appt0.getStartHour();
      assertEquals(0, appt0.getStartYear());
      assertEquals(2859, appt0.getStartMonth());
      assertEquals(1, int0);
      assertFalse(appt0.getValid());
      assertEquals(1, appt0.getStartMinute());
      assertEquals(1, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 0, (-21), 0, "ffolBDJ#nz sD'", "ffolBDJ#nz sD'");
      int int0 = appt0.getStartDay();
      assertEquals("ffolBDJ#nz sD'", appt0.getDescription());
      assertFalse(appt0.getValid());
      assertEquals(-21, appt0.getStartMonth());
      assertEquals(0, appt0.getStartYear());
      assertEquals("ffolBDJ#nz sD'", appt0.getTitle());
      assertEquals(0, int0);
      assertEquals(0, appt0.getStartMinute());
      assertEquals(0, appt0.getStartHour());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, (-661), (-2648), 916, "", "");
      int int0 = appt0.getStartDay();
      assertEquals(0, appt0.getStartMinute());
      assertEquals(0, appt0.getStartHour());
      assertEquals(916, appt0.getStartYear());
      assertFalse(appt0.getValid());
      assertEquals(-2648, appt0.getStartMonth());
      assertEquals((-661), int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Appt appt0 = new Appt((-2106), (-2106), (-2106), 1732, (-2106), "*0j`uJY0 *7!hf2K", "*0j`uJY0 *7!hf2K");
      appt0.setDescription("(U");
      assertEquals("(U", appt0.getDescription());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Appt appt0 = new Appt(1916, (-2950), 0, (-166), 1916, "Iv", "");
      assertEquals("", appt0.getDescription());
      
      appt0.setDescription((String) null);
      assertEquals(0, appt0.getStartDay());
      assertFalse(appt0.getValid());
      assertEquals("Iv", appt0.getTitle());
      assertEquals(1916, appt0.getStartYear());
      assertEquals(-166, appt0.getStartMonth());
      assertEquals(-2950, appt0.getStartMinute());
      assertEquals(1916, appt0.getStartHour());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Appt appt0 = new Appt(31, 31, 31, 31, 31, "Mg", "Mg");
      appt0.setTitle("Mg");
      assertEquals(31, appt0.getStartHour());
      assertEquals(31, appt0.getStartMinute());
      assertEquals(31, appt0.getStartMonth());
      assertEquals("Mg", appt0.getDescription());
      assertEquals(31, appt0.getStartDay());
      assertEquals("Mg", appt0.getTitle());
      assertFalse(appt0.getValid());
      assertEquals(31, appt0.getStartYear());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Appt appt0 = new Appt((-2106), (-2106), (-2106), 1732, (-2106), "*0j`uJY0 *7!hf2K", "*0j`uJY0 *7!hf2K");
      assertEquals("*0j`uJY0 *7!hf2K", appt0.getTitle());
      
      appt0.setTitle((String) null);
      assertEquals(-2106, appt0.getStartYear());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Appt appt0 = new Appt((-1), (-1), (-1), (-1), 2166, ":", ":");
      String string0 = appt0.getTitle();
      assertEquals(-1, appt0.getStartMonth());
      assertEquals(-1, appt0.getStartHour());
      assertFalse(appt0.getValid());
      assertEquals(":", string0);
      assertEquals(":", appt0.getDescription());
      assertEquals(2166, appt0.getStartYear());
      assertEquals(-1, appt0.getStartDay());
      assertEquals(-1, appt0.getStartMinute());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Appt appt0 = new Appt((-1940), (-1), 1371, (-1), 2450, "X94<1[Koz[-s", "Jgg*N");
      int int0 = appt0.getStartDay();
      assertEquals(1371, int0);
      assertEquals(-1940, appt0.getStartHour());
      assertEquals(2450, appt0.getStartYear());
      assertFalse(appt0.getValid());
      assertEquals(-1, appt0.getStartMinute());
      assertEquals(-1, appt0.getStartMonth());
      assertEquals("Jgg*N", appt0.getDescription());
      assertEquals("X94<1[Koz[-s", appt0.getTitle());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Appt appt0 = new Appt((-48), (-48), (-48), (-48), (-48), "", "");
      boolean boolean0 = appt0.getValid();
      assertEquals(-48, appt0.getStartMonth());
      assertEquals(-48, appt0.getStartYear());
      assertEquals(-48, appt0.getStartHour());
      assertFalse(boolean0);
      assertEquals(-48, appt0.getStartMinute());
      assertEquals(-48, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Appt appt0 = new Appt((-3812), (-602), 0, (-3812), (-602), (String) null, (String) null);
      int int0 = appt0.getStartHour();
      assertEquals((-3812), int0);
      assertEquals(-602, appt0.getStartMinute());
      assertEquals(-3812, appt0.getStartMonth());
      assertEquals(-602, appt0.getStartYear());
      assertFalse(appt0.getValid());
      assertEquals(0, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Appt appt0 = new Appt((-2106), (-2106), (-2106), 1732, (-2106), "*0j`uJY0 *7!hf2K", "*0j`uJY0 *7!hf2K");
      int int0 = appt0.getStartYear();
      assertEquals((-2106), int0);
      assertEquals(-2106, appt0.getStartDay());
      assertEquals("*0j`uJY0 *7!hf2K", appt0.getDescription());
      assertEquals(-2106, appt0.getStartHour());
      assertFalse(appt0.getValid());
      assertEquals("*0j`uJY0 *7!hf2K", appt0.getTitle());
      assertEquals(1732, appt0.getStartMonth());
      assertEquals(-2106, appt0.getStartMinute());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Appt appt0 = new Appt(1322, 1322, 1322, 321, 321, "x", "");
      int int0 = appt0.getStartMinute();
      assertEquals(321, appt0.getStartMonth());
      assertEquals(1322, int0);
      assertEquals("", appt0.getDescription());
      assertEquals(1322, appt0.getStartHour());
      assertEquals("x", appt0.getTitle());
      assertEquals(1322, appt0.getStartDay());
      assertFalse(appt0.getValid());
      assertEquals(321, appt0.getStartYear());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Appt appt0 = new Appt(11, 11, 1945, 11, 11, "}o&Bn,V)k&", "}o&Bn,V)k&");
      appt0.setStartDay(11);
      appt0.setStartHour(0);
      appt0.toString();
      assertEquals(0, appt0.getStartHour());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Appt appt0 = new Appt(20, 20, 1, 1, 20, "?", "?");
      String string0 = appt0.toString();
      assertEquals("\t1/1/20 at 8:20pm ,?, ?\n", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Appt appt0 = new Appt(23, 23, (-976), 1701, (-1069), "", "!pe0/ok;/d_,6");
      String string0 = appt0.toString();
      assertEquals(23, appt0.getStartHour());
      assertEquals("", appt0.getTitle());
      assertEquals(1701, appt0.getStartMonth());
      assertEquals(-1069, appt0.getStartYear());
      assertEquals(23, appt0.getStartMinute());
      assertNull(string0);
      assertEquals("!pe0/ok;/d_,6", appt0.getDescription());
      assertEquals(-976, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Appt appt0 = new Appt(52, 52, 52, 52, 52, "Sq=jA~}Cz7(A)3)yqw", "Sq=jA~}Cz7(A)3)yqw");
      appt0.setStartHour(1);
      appt0.setStartMinute(611);
      assertEquals(611, appt0.getStartMinute());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Appt appt0 = new Appt(0, (-1338), 0, 1225, (-1338), "", "3");
      String string0 = appt0.getDescription();
      assertEquals(0, appt0.getStartHour());
      assertFalse(appt0.getValid());
      assertEquals(-1338, appt0.getStartYear());
      assertEquals(-1338, appt0.getStartMinute());
      assertEquals(0, appt0.getStartDay());
      assertEquals("", appt0.getTitle());
      assertEquals(1225, appt0.getStartMonth());
      assertEquals("3", string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Appt appt0 = new Appt(1322, 1322, 1322, 321, 321, "x", "");
      int int0 = appt0.getStartMonth();
      assertEquals(1322, appt0.getStartHour());
      assertEquals("", appt0.getDescription());
      assertEquals(321, appt0.getStartYear());
      assertFalse(appt0.getValid());
      assertEquals(321, int0);
      assertEquals(1322, appt0.getStartMinute());
      assertEquals("x", appt0.getTitle());
      assertEquals(1322, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Appt appt0 = new Appt((-1456), (-1456), (-1456), (-1456), (-1456), (String) null, (String) null);
      String string0 = appt0.getDescription();
      assertNotNull(string0);
      assertEquals(-1456, appt0.getStartYear());
      assertFalse(appt0.getValid());
      assertEquals(-1456, appt0.getStartHour());
      assertEquals(-1456, appt0.getStartMinute());
      assertEquals(-1456, appt0.getStartMonth());
      assertEquals(-1456, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Appt appt0 = new Appt(23, 23, (-976), 1701, (-1069), "", "!pe0/ok;/d_,6");
      appt0.setStartYear(11);
      assertEquals(11, appt0.getStartYear());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Appt appt0 = new Appt(23, 23, (-976), 1701, (-1069), "", "!pe0/ok;/d_,6");
      appt0.setStartMonth((-1069));
      appt0.setStartDay(31);
      assertEquals(31, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Appt appt0 = new Appt(11, 11, 1945, 11, 11, "}o&Bn,V)k&", "}o&Bn,V)k&");
      assertEquals(1945, appt0.getStartDay());
      
      appt0.setStartDay(11);
      String string0 = appt0.toString();
      assertEquals("\t11/11/11 at 11:11am ,}o&Bn,V)k&, }o&Bn,V)k&\n", string0);
  }
}
