/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 16 23:43:05 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import edu.osu.cs362.sortBody;
import java.nio.channels.NotYetConnectedException;
import java.nio.channels.ReadableByteChannel;
import java.nio.channels.SocketChannel;
import java.util.NoSuchElementException;
import java.util.Scanner;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class sortBody_ESTest extends sortBody_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      int[] intArray0 = new int[0];
      sortBody0.HighLevel(intArray0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      int[] intArray0 = new int[4];
      intArray0[0] = (-7475);
      sortBody0.LowestLevel(intArray0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      int[] intArray0 = new int[5];
      sortBody0.tempArrayb = intArray0;
      sortBody sortBody1 = new sortBody();
      sortBody1.tempArray = sortBody0.tempArrayb;
      // Undeclared exception!
      try { 
        sortBody1.runSort();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 5
         //
         assertThrownBy("edu.osu.cs362.sortBody", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      SocketChannel socketChannel0 = SocketChannel.open();
      Scanner scanner0 = new Scanner((ReadableByteChannel) socketChannel0);
      sortBody0.keyboard = scanner0;
      // Undeclared exception!
      try { 
        sortBody0.run();
        fail("Expecting exception: NotYetConnectedException");
      
      } catch(NotYetConnectedException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("sun.nio.ch.SocketChannelImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      sortBody0.keyboard = null;
      // Undeclared exception!
      try { 
        sortBody0.run();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("edu.osu.cs362.sortBody", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      int[] intArray0 = new int[7];
      sortBody0.tempArray = intArray0;
      // Undeclared exception!
      try { 
        sortBody0.run();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 7
         //
         assertThrownBy("edu.osu.cs362.sortBody", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      // Undeclared exception!
      try { 
        sortBody0.merge((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("edu.osu.cs362.sortBody", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      int[] intArray0 = new int[9];
      // Undeclared exception!
      try { 
        sortBody0.merge(intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 8
         //
         assertThrownBy("edu.osu.cs362.sortBody", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      // Undeclared exception!
      try { 
        sortBody0.displayArray((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("edu.osu.cs362.sortBody", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      sortBody0.keyboard = null;
      // Undeclared exception!
      try { 
        sortBody0.RunAgain();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("edu.osu.cs362.sortBody", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      // Undeclared exception!
      try { 
        sortBody0.MiddleLevel((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("edu.osu.cs362.sortBody", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      // Undeclared exception!
      try { 
        sortBody0.LowestLevel((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("edu.osu.cs362.sortBody", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      int[] intArray0 = new int[9];
      // Undeclared exception!
      try { 
        sortBody0.LowestLevel(intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 8
         //
         assertThrownBy("edu.osu.cs362.sortBody", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      // Undeclared exception!
      try { 
        sortBody0.HighLevel((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("edu.osu.cs362.sortBody", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      SystemInUtil.addInputLine("j_*T{&/jJT)K)r#C");
      // Undeclared exception!
      try { 
        sortBody0.RunAgain();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      int[] intArray0 = new int[8];
      sortBody0.runSort();
      sortBody0.merge(intArray0);
      sortBody0.MiddleLevel(intArray0);
      assertArrayEquals(new int[] {2, 6, 7, 4, 5, 5, 2222, 3}, intArray0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      int[] intArray0 = new int[8];
      intArray0[1] = 3832;
      intArray0[2] = (int) '\'';
      sortBody0.MiddleLevel(intArray0);
      assertArrayEquals(new int[] {0, 0, 0, 0, 0, 0, 0, 0}, intArray0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      int[] intArray0 = new int[4];
      intArray0[1] = (-890);
      // Undeclared exception!
      try { 
        sortBody0.MiddleLevel(intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 4
         //
         assertThrownBy("edu.osu.cs362.sortBody", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      sortBody0.displayArray(sortBody0.tempArray);
      assertEquals('\u0000', sortBody0.PlayAgain);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      SystemInUtil.addInputLine("n");
      sortBody sortBody0 = new sortBody();
      sortBody0.run();
      assertEquals('\u0000', sortBody0.PlayAgain);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      SystemInUtil.addInputLine("Do you wish to repeat? please enter y/n:\n");
      sortBody sortBody0 = new sortBody();
      // Undeclared exception!
      try { 
        sortBody0.run();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      int[] intArray0 = new int[4];
      intArray0[0] = (-7475);
      // Undeclared exception!
      try { 
        sortBody0.MiddleLevel(intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 4
         //
         assertThrownBy("edu.osu.cs362.sortBody", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      int[] intArray0 = new int[5];
      intArray0[0] = (-1790088671);
      intArray0[1] = 225;
      // Undeclared exception!
      try { 
        sortBody0.MiddleLevel(intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 5
         //
         assertThrownBy("edu.osu.cs362.sortBody", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      sortBody0.displayTempArray(sortBody0.tempArray);
      assertEquals('\u0000', sortBody0.PlayAgain);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      sortBody0.beginArrayParameter();
      assertEquals('\u0000', sortBody0.PlayAgain);
  }
}
