/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 16 23:45:34 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import edu.osu.cs362.sortBody;
import java.net.URISyntaxException;
import java.nio.channels.NotYetConnectedException;
import java.nio.channels.ReadableByteChannel;
import java.nio.channels.SocketChannel;
import java.util.NoSuchElementException;
import java.util.Scanner;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockURI;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class sortBody_ESTest extends sortBody_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      int[] intArray0 = new int[1];
      sortBody0.RunProgramAgain = "";
      sortBody0.PlayAgain = '!';
      sortBody0.LowestLevel(intArray0);
      intArray0[0] = (int) '!';
      sortBody0.tempArray = intArray0;
      sortBody0.PlayAgain = 'T';
      sortBody0.displayArray(intArray0);
      sortBody0.merge(intArray0);
      // Undeclared exception!
      try { 
        sortBody0.RunAgain();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1
         //
         assertThrownBy("edu.osu.cs362.sortBody", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      int[] intArray0 = new int[6];
      intArray0[0] = 9;
      intArray0[1] = (int) '\u0000';
      intArray0[2] = (int) '\u0000';
      intArray0[3] = (int) '\u0000';
      intArray0[4] = (int) '\u0000';
      intArray0[5] = (int) '\u0000';
      sortBody0.LowestLevel(intArray0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      sortBody0.tempArray = null;
      sortBody0.tempArray = null;
      // Undeclared exception!
      try { 
        sortBody0.HighLevel((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("edu.osu.cs362.sortBody", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      sortBody0.beginArrayParameter();
      // Undeclared exception!
      try { 
        sortBody0.LowestLevel((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("edu.osu.cs362.sortBody", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      sortBody0.runSort();
      int[] intArray0 = new int[5];
      intArray0[0] = (int) '\u0000';
      sortBody0.runSort();
      intArray0[1] = (int) '\u0000';
      intArray0[2] = (int) '\u0000';
      intArray0[3] = (int) '\u0000';
      intArray0[4] = (int) '\u0000';
      sortBody0.merge(intArray0);
      char char0 = sortBody0.PlayAgain;
      sortBody0.tempArrayb = intArray0;
      sortBody sortBody1 = new sortBody();
      sortBody1.tempArray = sortBody0.tempArrayb;
      sortBody1.displayArray(intArray0);
      char char1 = sortBody1.PlayAgain;
      sortBody0.tempArrayb = sortBody1.tempArray;
      sortBody0.MiddleLevel(sortBody1.tempArrayb);
      int[] intArray1 = sortBody1.tempArrayb;
      // Undeclared exception!
      try { 
        sortBody1.runSort();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 5
         //
         assertThrownBy("edu.osu.cs362.sortBody", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      int[] intArray0 = new int[7];
      intArray0[0] = (int) '\u0000';
      sortBody0.tempArray = intArray0;
      intArray0[1] = (int) '\u0000';
      intArray0[2] = (int) '\u0000';
      intArray0[3] = (int) '\u0000';
      intArray0[4] = (int) '\u0000';
      intArray0[5] = (int) '\u0000';
      intArray0[6] = (int) '\u0000';
      sortBody0.tempArrayb = intArray0;
      // Undeclared exception!
      try { 
        sortBody0.run();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 7
         //
         assertThrownBy("edu.osu.cs362.sortBody", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      sortBody0.runSort();
      // Undeclared exception!
      try { 
        sortBody0.MiddleLevel((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("edu.osu.cs362.sortBody", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      int[] intArray0 = new int[9];
      intArray0[0] = 0;
      intArray0[1] = (int) '\u0000';
      intArray0[2] = (int) '\u0000';
      intArray0[3] = 1958;
      intArray0[4] = (int) '\u0000';
      intArray0[5] = 0;
      intArray0[6] = (int) '\u0000';
      intArray0[7] = (int) '\u0000';
      intArray0[8] = (int) '\u0000';
      // Undeclared exception!
      try { 
        sortBody0.merge(intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 8
         //
         assertThrownBy("edu.osu.cs362.sortBody", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      // Undeclared exception!
      try { 
        sortBody0.displayArray((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("edu.osu.cs362.sortBody", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      int[] intArray0 = new int[8];
      sortBody0.MiddleLevel(intArray0);
      intArray0[0] = (int) '\u0000';
      intArray0[1] = 3832;
      intArray0[2] = (int) '\u0000';
      intArray0[3] = (int) '\u0000';
      intArray0[4] = (int) '\u0000';
      sortBody0.displayArray(intArray0);
      sortBody0.runSort();
      intArray0[5] = (-710);
      intArray0[6] = (int) '\u0000';
      intArray0[7] = (int) '\u0000';
      sortBody0.merge(intArray0);
      sortBody0.displayArray(intArray0);
      sortBody0.displayTempArray(intArray0);
      sortBody0.merge(intArray0);
      int[] intArray1 = new int[21];
      intArray1[0] = 3;
      intArray1[1] = 0;
      intArray1[2] = (-710);
      intArray1[3] = 3;
      intArray1[4] = (int) '\u0000';
      intArray1[5] = (-710);
      // Undeclared exception!
      try { 
        sortBody0.MiddleLevel(intArray1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 8
         //
         assertThrownBy("edu.osu.cs362.sortBody", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      sortBody0.RunProgramAgain = null;
      sortBody0.runSort();
      sortBody0.tempArrayb = sortBody0.tempArray;
      sortBody0.PlayAgain = 'D';
      sortBody0.MiddleLevel(sortBody0.tempArray);
      sortBody0.displayArray(sortBody0.tempArray);
      // Undeclared exception!
      try { 
        sortBody0.RunAgain();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      int[] intArray0 = new int[4];
      intArray0[0] = (int) '\u0000';
      intArray0[1] = (-890);
      intArray0[2] = (int) '\u0000';
      intArray0[3] = (int) '\u0000';
      // Undeclared exception!
      try { 
        sortBody0.MiddleLevel(intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 4
         //
         assertThrownBy("edu.osu.cs362.sortBody", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      int[] intArray0 = new int[4];
      intArray0[0] = (-7475);
      intArray0[1] = (int) '\u0000';
      intArray0[2] = (int) '\u0000';
      intArray0[3] = (int) '\u0000';
      sortBody0.displayArray(intArray0);
      sortBody0.LowestLevel(intArray0);
      // Undeclared exception!
      try { 
        sortBody0.MiddleLevel(intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 4
         //
         assertThrownBy("edu.osu.cs362.sortBody", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      int[] intArray0 = new int[9];
      intArray0[0] = (int) '\u0000';
      intArray0[1] = (int) '\u0000';
      // Undeclared exception!
      try { 
        sortBody0.LowestLevel(intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 8
         //
         assertThrownBy("edu.osu.cs362.sortBody", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      sortBody0.PlayAgain = 'y';
      sortBody0.RunProgramAgain = null;
      sortBody0.RunProgramAgain = "J";
      // Undeclared exception!
      try { 
        sortBody0.merge((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("edu.osu.cs362.sortBody", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      FileSystemHandling.setPermissions((EvoSuiteFile) null, false, false, false);
      SocketChannel socketChannel0 = SocketChannel.open();
      Scanner scanner0 = new Scanner((ReadableByteChannel) socketChannel0);
      sortBody0.keyboard = scanner0;
      // Undeclared exception!
      try { 
        sortBody0.run();
        fail("Expecting exception: NotYetConnectedException");
      
      } catch(NotYetConnectedException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("sun.nio.ch.SocketChannelImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      int[] intArray0 = new int[4];
      intArray0[0] = (int) '\u0000';
      FileSystemHandling.createFolder((EvoSuiteFile) null);
      intArray0[1] = (int) '\u0000';
      intArray0[2] = 11;
      intArray0[3] = (int) '\u0000';
      sortBody0.displayArray(intArray0);
      int[] intArray1 = new int[1];
      intArray1[0] = (int) '\u0000';
      sortBody0.tempArrayb = intArray1;
      sortBody0.HighLevel(intArray1);
      sortBody0.keyboard = null;
      sortBody sortBody1 = new sortBody();
      sortBody1.tempArray = sortBody0.tempArrayb;
      sortBody1.displayArray(intArray0);
      sortBody1.keyboard = null;
      FileSystemHandling.shouldThrowIOException((EvoSuiteFile) null);
      // Undeclared exception!
      try { 
        sortBody1.RunAgain();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("edu.osu.cs362.sortBody", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      SystemInUtil.addInputLine("Do you wish to repeat? please enter y/n:\n");
      FileSystemHandling.setPermissions((EvoSuiteFile) null, true, true, true);
      sortBody sortBody0 = new sortBody();
      // Undeclared exception!
      try { 
        sortBody0.run();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      int[] intArray0 = new int[8];
      sortBody0.MiddleLevel(intArray0);
      intArray0[0] = (int) '\u0000';
      sortBody0.PlayAgain = '\'';
      intArray0[1] = 3832;
      intArray0[2] = (int) '\'';
      sortBody0.MiddleLevel(intArray0);
      intArray0[3] = (int) '\'';
      sortBody0.LowestLevel(intArray0);
      intArray0[1] = (int) '\'';
      sortBody0.keyboard = null;
      sortBody0.displayArray(intArray0);
      sortBody0.runSort();
      intArray0[5] = 1568;
      intArray0[6] = (int) '\'';
      intArray0[7] = (int) '\'';
      sortBody0.merge(intArray0);
      sortBody0.displayArray(intArray0);
      sortBody0.displayTempArray(intArray0);
      sortBody0.merge(intArray0);
      // Undeclared exception!
      try { 
        sortBody0.run();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("edu.osu.cs362.sortBody", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      int[] intArray0 = new int[0];
      sortBody0.HighLevel(intArray0);
      sortBody0.tempArray = intArray0;
      try { 
        MockURI.URI((String) null, "\"( P[),G=`", "\"( P[),G=`", "\"( P[),G=`", "\"( P[),G=`");
        fail("Expecting exception: URISyntaxException");
      
      } catch(URISyntaxException e) {
         //
         // Illegal character in hostname at index 2: //%22(%20P[),G=%60%22(%20P%5B),G=%60?%22(%20P[),G=%60#%22(%20P[),G=%60
         //
         assertThrownBy("java.net.URI$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      FileSystemHandling.shouldThrowIOException((EvoSuiteFile) null);
      sortBody sortBody0 = new sortBody();
      int[] intArray0 = new int[7];
      intArray0[0] = (int) '\u0000';
      intArray0[1] = (int) '\u0000';
      intArray0[3] = (int) '\u0000';
      intArray0[4] = (int) '\u0000';
      intArray0[5] = (int) '\u0000';
      intArray0[6] = (int) '\u0000';
      sortBody0.runSort();
      sortBody0.displayArray(intArray0);
      int[] intArray1 = new int[1];
      sortBody0.runSort();
      sortBody0.MiddleLevel(intArray0);
      intArray1[0] = (int) '\u0000';
      SystemInUtil.addInputLine("j_*T{&/jJT)K)r#C");
      // Undeclared exception!
      try { 
        sortBody0.RunAgain();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      int[] intArray0 = new int[1];
      intArray0[0] = (int) '\u0000';
      sortBody0.LowestLevel(intArray0);
      sortBody0.LowestLevel(intArray0);
      sortBody0.RunProgramAgain = null;
      sortBody0.runSort();
      sortBody0.merge(intArray0);
      sortBody0.beginArrayParameter();
      // Undeclared exception!
      try { 
        sortBody0.RunAgain();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      SystemInUtil.addInputLine("n");
      FileSystemHandling.setPermissions((EvoSuiteFile) null, false, false, true);
      sortBody sortBody0 = new sortBody();
      sortBody0.run();
      String string0 = "";
      int[] intArray0 = new int[3];
      intArray0[0] = (int) '\u0000';
      intArray0[1] = (int) '\u0000';
      sortBody0.LowestLevel(intArray0);
      intArray0[2] = (int) '\u0000';
      // Undeclared exception!
      try { 
        sortBody0.MiddleLevel(intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 3
         //
         assertThrownBy("edu.osu.cs362.sortBody", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      SystemInUtil.addInputLine("n");
      sortBody sortBody0 = new sortBody();
      sortBody0.run();
      String string0 = "";
      int[] intArray0 = new int[3];
      intArray0[1] = (int) '\u0000';
      sortBody0.LowestLevel(intArray0);
      intArray0[2] = (int) '\u0000';
      // Undeclared exception!
      try { 
        sortBody0.MiddleLevel(intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 3
         //
         assertThrownBy("edu.osu.cs362.sortBody", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      sortBody sortBody0 = new sortBody();
      int[] intArray0 = new int[5];
      intArray0[0] = (-1790088671);
      sortBody0.LowestLevel(intArray0);
      intArray0[1] = 225;
      sortBody0.RunProgramAgain = sortBody0.RunProgramAgain;
      intArray0[2] = (int) '\u0000';
      intArray0[3] = (int) '\u0000';
      intArray0[4] = (int) '\u0000';
      sortBody0.LowestLevel(intArray0);
      sortBody0.displayTempArray(intArray0);
      // Undeclared exception!
      try { 
        sortBody0.MiddleLevel(intArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 5
         //
         assertThrownBy("edu.osu.cs362.sortBody", e);
      }
  }
}
